/*
 * Copyright � 2025-Present The DClare Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"),
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//!\ This file has been generated, any modification will be lost /!\\

import { Hydrator } from '../hydrator';
import { OauthFlowCollectionDefinition } from './oauth-flow-collection-definition';
import { Type } from 'class-transformer';

/**
 * Represents the definition of the authentication method used to secure access to an exposed interface
 */
export class SecuritySchemeDefinition extends Hydrator<SecuritySchemeDefinition> {
  constructor(model?: Partial<SecuritySchemeDefinition>) {
    super(model);
    if (model) {
      if (model.flows) this.flows = new OauthFlowCollectionDefinition(model.flows);
    }
  }

  /**
   * Gets/sets an object used to configure an hosted agent
   */
  type: string;

  /**
   * Gets/sets a short description for security scheme. CommonMark syntax MAY be used for rich text representation
   */
  description?: string;

  /**
   * Gets/sets the name of the header, query or cookie parameter to be used<para></para>  Required if `type` is set to `apiKey`
   */
  name?: string;

  /**
   * Gets/sets the location of the API key<para></para>  Required if `type` is set to `apiKey`
   */
  in?: string;

  /**
   * Gets/sets the name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235<para></para>  Required if `type` is set to `http`
   */
  scheme?: string;

  /**
   * Gets/sets an hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes<para></para>  Applies if `type` is set to `http`, otherwise ignored
   */
  bearerFormat?: string;

  /**
   * Gets/sets an object containing configuration information for the flow types supported<para></para>  Required if `type` is set to `oauth2`
   */
  @Type(() => OauthFlowCollectionDefinition)
  flows?: OauthFlowCollectionDefinition;

  /**
   * Gets/sets the OpenId Connect URL to discover OAuth2 configuration values<para></para>  Required if `type` is set to `openIdConnect`
   */
  openIdConnectUrl?: string;
}
