name: Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.git*'
      - '.github/**'
      - 'submodules/**'
      - 'templates/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.git*'
      - '.github/**'
      - 'submodules/**'
      - 'templates/**'
  workflow_call:

permissions:
  contents: read

jobs:
  build-and-test:

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd719

    - name: Setup Node.js
      uses: actions/setup-node@49933ea
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: |
          20.0.x
          22.0.x
          23.0.x

    - name: Install Dependencies
      run: npm ci

    - name: Build Library
      run: npm run build

    - name: Run Tests
      run: npm test

