name: Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.git*'
      - '.github/**'
      - 'submodules/**'
      - 'templates/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.git*'
      - '.github/**'
      - 'submodules/**'
      - 'templates/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:

    name: Build and Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '22.x', latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: npm ci

    - name: Build Library
      run: npm run build

    - name: Run Tests
      run: npm test

